'use client';
import { FormEvent, useEffect, useState } from 'react';
type Project={id:string;title:string;surveyUrl:string;status:string;targetRespondents:number;estimatedMinutes:number;rewardPerResponse:number;rewardPool:number;platformFee:number;processingCost:number;totalCost:number;payoutRatio:number;_count:{participations:number}};
export default function ResearcherPage(){
 const [projects,setProjects]=useState<Project[]>([]); const [msg,setMsg]=useState('');
 const load=()=>fetch('/api/projects').then(r=>r.json()).then(setProjects); useEffect(()=>{load()},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setMsg('');const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());const r=await fetch('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setMsg(j.error||'생성 실패');return}e.currentTarget.reset();setMsg('프로젝트가 생성됐습니다. 결제(샌드박스) 후 모집을 시작하세요.');load()}
 async function activate(id:string){const r=await fetch('/api/projects/activate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:id,idempotencyKey:`activate-${id}`})});const j=await r.json();setMsg(r.ok?'샌드박스 결제가 승인되어 모집을 시작했습니다.':j.error);load()}
 return <><section className="hero"><div><span className="badge">Verified Respondent Marketplace</span><h1>설문 링크만 넣고<br/>필요한 사람을 모으세요.</h1><p className="muted">설문 제작기가 아닙니다. 실제 응답자를 찾고, 검증하고, 응답 보상을 투명하게 연결합니다.</p><div className="notice">MVP는 실제 DB와 상태 전이를 사용합니다. 결제와 본인인증만 로컬 sandbox adapter입니다.</div></div><form className="card" onSubmit={create}><h2>새 조사 만들기</h2><div className="grid"><div className="field full"><label>조사 제목</label><input name="title" required placeholder="예: 커피 이용 경험 조사"/></div><div className="field full"><label>외부 설문 URL</label><input name="surveyUrl" required type="url" placeholder="https://forms.google.com/..."/></div><div className="field"><label>최소 나이</label><input name="minAge" type="number" defaultValue="20" min="14"/></div><div className="field"><label>최대 나이</label><input name="maxAge" type="number" defaultValue="39" min="14"/></div><div className="field"><label>지역</label><select name="region" defaultValue="전국"><option>전국</option><option>서울</option><option>경기</option><option>부산</option></select></div><div className="field"><label>필요 인원</label><input name="targetRespondents" type="number" defaultValue="10" min="1"/></div><div className="field"><label>예상 시간(분)</label><input name="estimatedMinutes" type="number" defaultValue="5" min="1"/></div><div className="field"><label>1인 보상(원)</label><input name="rewardPerResponse" type="number" defaultValue="1000" min="100" step="100"/></div><div className="field full"><button type="submit">비용 계산하고 프로젝트 만들기</button></div></div></form></section>{msg&&<div className="notice">{msg}</div>}<section className="section"><h2>내 프로젝트</h2><div className="list">{projects.map(p=><div className="survey" key={p.id}><div><div className="row"><strong>{p.title}</strong><span className="badge">{p.status}</span></div><p className="muted">{p.estimatedMinutes}분 · 1명당 {p.rewardPerResponse.toLocaleString()}원 · {p._count.participations}/{p.targetRespondents}명 참여</p><small className="muted">응답자 {p.rewardPool.toLocaleString()}원 · 처리 {p.processingCost.toLocaleString()}원 · 운영 {p.platformFee.toLocaleString()}원 · 지급률 {(p.payoutRatio*100).toFixed(1)}%</small></div><div><div className="money">{p.totalCost.toLocaleString()}원</div>{p.status==='DRAFT'&&<button onClick={()=>activate(p.id)}>결제하고 모집 시작</button>}</div></div>)}{projects.length===0&&<p className="muted">아직 프로젝트가 없습니다.</p>}</div></section></>}
