'use client';
import { useEffect,useState } from 'react';
type Survey={id:string;title:string;surveyUrl:string;estimatedMinutes:number;rewardPerResponse:number;region:string|null;minAge:number;maxAge:number;remaining:number};
type Started={participationId:string;completionCode:string;surveyUrl:string};
export default function Respondent(){const [respondentId,setRespondentId]=useState('demo-seoul-29');const [surveys,setSurveys]=useState<Survey[]>([]);const [started,setStarted]=useState<Started|null>(null);const [msg,setMsg]=useState('');
 const load=()=>fetch(`/api/respondent?respondentId=${respondentId}`).then(r=>r.json()).then(j=>setSurveys(j.surveys||[]));useEffect(()=>{load()},[respondentId]);
 async function start(projectId:string){const r=await fetch('/api/participations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId,respondentId})});const j=await r.json();if(r.ok){setStarted(j);window.open(j.surveyUrl,'_blank')}else setMsg(j.error)}
 async function verify(){if(!started)return;const code=(document.getElementById('code') as HTMLInputElement).value;const r=await fetch('/api/participations/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({participationId:started.participationId,completionCode:code,idempotencyKey:`reward-${started.participationId}`})});const j=await r.json();setMsg(r.ok?`검증 완료. ${j.reward.amount.toLocaleString()}원이 보상 Ledger에 반영됐습니다.`:j.error);if(r.ok)setStarted(null);load()}
 return <><section><span className="badge">응답자 앱 MVP</span><h1>내가 참여할 수 있는 조사</h1><div className="row"><label>데모 응답자</label><select style={{width:220}} value={respondentId} onChange={e=>setRespondentId(e.target.value)}><option value="demo-seoul-29">김응답 · 29세 · 서울</option><option value="demo-busan-34">이패널 · 34세 · 부산</option><option value="demo-seoul-41">박리서치 · 41세 · 서울</option></select></div>{msg&&<div className="notice">{msg}</div>}<div className="list">{surveys.map(s=><div className="survey" key={s.id}><div><strong>{s.title}</strong><p className="muted">예상 {s.estimatedMinutes}분 · {s.minAge}~{s.maxAge}세 · {s.region||'전국'} · 남은 인원 {s.remaining}명</p></div><div><div className="money">{s.rewardPerResponse.toLocaleString()}원</div><button onClick={()=>start(s.id)}>참여하기</button></div></div>)}{surveys.length===0&&<p className="muted">현재 조건에 맞는 모집 중 조사가 없습니다.</p>}</div></section>{started&&<section className="card section"><h2>완료 검증</h2><p>외부 설문 완료 후 아래 완료 코드를 입력하세요.</p><div className="notice">데모에서는 실제 integration callback 대신 발급된 completion code를 사용합니다. 테스트 코드: <strong>{started.completionCode}</strong></div><div className="row"><input id="code" placeholder="완료 코드" style={{maxWidth:260}}/><button onClick={verify}>검증하고 보상 받기</button></div></section>}</>}
